config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tax_rules
  resources :tax_calculations

  root to: 'pages#home'
end

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3 bg-light">
  <div class="container">
    <span class="text-muted">Done by Jefferson Alvarez © <%= Time.now.year %></span>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
  <div class="container-fluid">
    <%= link_to "Tax calculator", root_path, class: "navbar-brand"%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <% if current_user.present? %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Tax calculations", tax_calculations_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Tax rules", tax_rules_path, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, class: "nav-link", method: :delete  %>
          </li>
        </ul>
      <% else %>
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        </ul>
      <% end %>
    </div>
  </div>
</nav>