config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :tax_rules
  resources :tax_calculations

  root to: 'pages#home'
end

app/models/tax_rule.rb
class TaxRule < ApplicationRecord
  validates :min_value, presence: true
  validates :percentage, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }

  belongs_to :user
  has_many :tax_calculations
end

app/controllers/tax_rules_controller.rb
class TaxRulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tax_rule, only: [:show, :edit, :update, :destroy]

  # GET /tax_rules
  # GET /tax_rules.json
  def index
    @tax_rules = current_user.tax_rules.all.order(min_value: :asc)
  end

  # GET /tax_rules/1
  # GET /tax_rules/1.json
  def show
  end

  # GET /tax_rules/new
  def new
    @tax_rule = current_user.tax_rules.new
  end

  # GET /tax_rules/1/edit
  def edit
  end

  # POST /tax_rules
  # POST /tax_rules.json
  def create
    @tax_rule = current_user.tax_rules.new(tax_rule_params)

    respond_to do |format|
      if @tax_rule.save
        format.html {
          flash[:success] = 'Tax rule was successfully created.'
          redirect_to @tax_rule
        }
        format.json { render :show, status: :created, location: @tax_rule }
      else
        error_messages = []
        @tax_rule.errors.messages.each do |attribute, message|
          error_messages << "#{attribute.to_s} #{message.to_s}"
        end
        format.html {
          flash[:error] = error_messages.join(', ').presence || 'There was an error, try again'
          render :new
        }
        format.json { render json: @tax_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tax_rules/1
  # PATCH/PUT /tax_rules/1.json
  def update
    respond_to do |format|
      if @tax_rule.update(tax_rule_params)
        format.html {
          flash[:success] = 'Tax rule was successfully updated.'
          redirect_to @tax_rule
        }
        format.json { render :show, status: :ok, location: @tax_rule }
      else
        error_messages = []
        @tax_rule.errors.messages.each do |attribute, message|
          error_messages << "#{attribute.to_s} #{message.to_s}"
        end
        format.html {
          flash[:error] = error_messages.join(', ').presence || 'There was an error, try again'
          render :edit
        }
        format.json { render json: @tax_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tax_rules/1
  # DELETE /tax_rules/1.json
  def destroy
    @tax_rule.destroy
    respond_to do |format|
      format.html {
        flash[:success] = 'Tax rule was successfully destroyed.'
        redirect_to tax_rules_url
      }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tax_rule
      @tax_rule = current_user.tax_rules.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tax_rule_params
      params.require(:tax_rule).permit(:min_value, :max_value, :percentage)
    end
end

app/helpers/tax_rules_helper.rb
module TaxRulesHelper
end

app/views/tax_rules/_form.html.erb
<%= form_with(model: tax_rule, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :min_value %>
    <%= form.text_field :min_value, type: 'number', required: true, placeholder: 'Minimum value', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :max_value %>
    <%= form.text_field :max_value, type: 'number', placeholder: 'Maximum value (Leave blank if there is no maximum value)', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :percentage %>
    <%= form.text_field :percentage, min: 0, max: 100, type: 'number', required: true, placeholder: 'Percentage', class: 'form-control' %>
  </div>

  <%= form.submit "#{ action_name.capitalize }  tax rule", class: 'btn btn-primary' %>
<% end %>

app/views/tax_rules/edit.html.erb
<h1>Edit tax rule</h1>

<%= render 'form', tax_rule: @tax_rule %>

app/views/tax_rules/index.html.erb
<h1>Tax rules</h1>

<%= link_to 'New tax rule', new_tax_rule_path, class: 'btn btn-primary' %>

<br /><br />

<table class="table">
  <thead>
    <tr>
      <th>Min value</th>
      <th>Max value</th>
      <th>Percentage</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tax_rules.each do |tax_rule| %>
      <tr>
        <td><%= tax_rule.min_value %></td>
        <td><%= tax_rule.max_value.present? ? tax_rule.max_value : 'Onward' %></td>
        <td><%= tax_rule.percentage %></td>
        <td><%= tax_rule.created_at %></td>
        <td><%= tax_rule.updated_at %></td>
        <td><%= link_to 'Show', tax_rule %></td>
        <td><%= link_to 'Edit', edit_tax_rule_path(tax_rule) %></td>
        <td><%= link_to 'Destroy', tax_rule, method: :delete, data: { confirm: 'Are you sure to delete this tax rule?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tax_rules/new.html.erb
<h1>New tax rule</h1>

<%= render 'form', tax_rule: @tax_rule %>

app/views/tax_rules/show.html.erb
<h1>Information of the tax rule</h1>
<p><b>Minimum value: </b><%= @tax_rule.min_value %></p>
<p><b>Maximum value: </b><%= @tax_rule.max_value.present? ? tax_rule.max_value : 'Onward' %></p>
<p><b>Percentage: </b><%= @tax_rule.percentage %></p>